- name: Install required packages
  apt:
    name:
      - python3-pip
    state: present
    update_cache: true
  become: yes

- name: Install required packages
  shell: pip3 install edgedb

- name: Set EdgeDB environment content
  set_fact:
    env_content:
      EDGEDB:
        HOST: "{{ server_ip }}"
        PORT: "{{ edgedb_parsed.port }}"
        USER: "{{ edgedb_parsed.user }}"
        PASSWORD: "{{ edgedb_parsed.password }}"
        DBNAME: "{{ db_branch_instance }}"
        TLS_CA: "{{ edgedb_parsed.tls_ca | replace('\n', '\\n') }}"
        TLS_SECURITY: "{{ edgedb_parsed.tls_security }}"

- name: Configure Python for Providerauth
  copy:
    dest: /home/ubuntu/{{ backend_deploy_branch }}.py
    content: |
      import json

      import edgedb

      default_esdl = """
      CONFIGURE CURRENT DATABASE SET
      ext::auth::AuthConfig::auth_signing_key := 'F2KHaJfHi9Dzd8+6DI7FB9IFIoJXnhz2rzG/UzCRE7jTtYxqgTHHydc8xnN6emDB3tlR99FvPsyJfcVLVcQ5odSQpceDXplBOP+N14+EBy2mV6rA/7W7azIEKebtr9TVKrpBTMTOLAXo08ZnA6lvjn0VMs95za6Pta7VW62hjcb8jy6yxulvvU5SWnwa0x2z401K0pLK7byDD5eNqgTl40YaeOGoQ0iCkSmGxvLxyQgCIz2IU0zUbBwC9bQsTDORvflunruJznHuMxwbfYo/czQIIGuawU0H+G3GJZ3hecZLQlvwYCyLF37PFQVrcNMtUuGyDy2OyYtYHru2GW5B7Q';

      CONFIGURE CURRENT DATABASE SET
      ext::auth::AuthConfig::token_time_to_live := <duration>"0";


      CONFIGURE CURRENT DATABASE
      INSERT ext::auth::EmailPasswordProviderConfig {
          require_verification := true,
      };

      CONFIGURE CURRENT DATABASE SET
      ext::auth::SMTPConfig::sender := 'hello@example.com';

      CONFIGURE CURRENT DATABASE SET
      ext::auth::SMTPConfig::host := 'localhost';

      CONFIGURE CURRENT DATABASE SET
      ext::auth::SMTPConfig::port := <int32>1025;

      CONFIGURE CURRENT DATABASE SET
      ext::auth::SMTPConfig::security := 'STARTTLSOrPlainText';

      CONFIGURE CURRENT DATABASE SET
      ext::auth::SMTPConfig::validate_certs := false;
      """

      allowed_urls = """
      CONFIGURE CURRENT BRANCH SET
      ext::auth::AuthConfig::allowed_redirect_urls := {
          "https://{{ dns_record }}/auth/verify",
          "https://{{ dns_record }}/db/{{ db_branch_instance }}/ext/auth/callback",
          "https://{{ frontend_url }}"
      };
      """

      def main():
          client = edgedb.create_client(
              host="{{ env_content.EDGEDB.HOST }}",
              port={{env_content.EDGEDB.PORT}},
              user="{{ env_content.EDGEDB.USER }}",
              password="{{ env_content.EDGEDB.PASSWORD }}",
              database="{{ env_content.EDGEDB.DBNAME }}",
              tls_ca="{{ env_content.EDGEDB.TLS_CA }}",
              tls_security="{{ env_content.EDGEDB.TLS_SECURITY }}"
          )    
          client.execute(default_esdl)

          client.execute(allowed_urls)

          client.close()


      if __name__ == "__main__":
          main()

- name: Run Python script
  shell: |
    python3 /home/ubuntu/{{ backend_deploy_branch }}.py
  ignore_errors: yes