- name: Create directory for GPG keyring
  ansible.builtin.file:
    path: /usr/local/share/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Download EdgeDB GPG keyring
  ansible.builtin.get_url:
    url: https://packages.edgedb.com/keys/edgedb-keyring.gpg
    dest: /usr/local/share/keyrings/edgedb-keyring.gpg
    mode: '0644'
  become: yes
  

- name: Add EdgeDB APT repository
  ansible.builtin.copy:
    content: "deb [signed-by=/usr/local/share/keyrings/edgedb-keyring.gpg] https://packages.edgedb.com/apt {{ ansible_distribution_release | lower }} main\n"
    dest: /etc/apt/sources.list.d/edgedb.list
    mode: '0644'
  become: yes

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes
